import admin from "./admin.json";
export const metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  
  // console.log(admin);
  return (
    <section className="grid grid-cols-12 ">
      <aside className=" col-span-12 sm:col-span-2 xl:col-span-1">
        <ul>
          {admin.map((item, ind) => {
            return (
              <li key={ind} className="p-2 border-2">
                {item.name}
              </li>
            );
          })}
        </ul>
      </aside>
      <aside>{children}</aside>
    </section>
  );
}
