export const role = "admin";

export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 8, 16, 8, 0),
    end: new Date(2024, 8, 16, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 8, 16, 9, 0),
    end: new Date(2024, 8, 16, 9, 45),
  },
  {
    title: "Bangla",
    allDay: false,
    start: new Date(2024, 8, 16, 10, 0),
    end: new Date(2024, 8, 16, 10, 45),
  },
  {
    title: "Bangla",
    allDay: false,
    start: new Date(2024, 8, 19, 10, 0),
    end: new Date(2024, 8, 19, 10, 45),
  },
];

export const teacherData = [
  {
    id: 1,
    teacherId: "T-1001",
    name: "John Doe",
    email: "john.doe@example.com",
    photo: "/image/noavatar.png",
    address: "123 Main St, Springfield, IL",
    dept: "Engineering",
    phone: "0198928383",
  },
  {
    id: 2,
    teacherId: "T-1002",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    photo: "/image/noavatar.png",
    address: "456 Elm St, Springfield, IL",
    dept: "Marketing",
    phone: "0198928383",
  },
  {
    id: 3,
    teacherId: "T-1003",
    name: "Sam Wilson",
    email: "sam.wilson@example.com",
    photo: "/image/noavatar.png",
    address: "789 Oak St, Springfield, IL",
    dept: "Finance",
    phone: "0198928383",
  },
  {
    id: 4,
    teacherId: "T-1004",
    name: "Lisa Johnson",
    email: "lisa.johnson@example.com",
    photo: "/image/noavatar.png",
    address: "101 Pine St, Springfield, IL",
    dept: "Human Resources",
    phone: "0198928383",
  },
  {
    id: 5,
    teacherId: "T-1005",
    name: "Tom Baker",
    email: "tom.baker@example.com",
    photo: "/image/noavatar.png",
    address: "202 Cedar St, Springfield, IL",
    dept: "Sales",
    phone: "0198928383",
  },
  {
    id: 6,
    teacherId: "T-1006",
    name: "Tom Lighter",
    email: "tom.lighter@example.com",
    photo: "/image/noavatar.png",
    address: "202 Cedar St, Springfield, IL",
    dept: "Sales",
    phone: "0198928383",
  },
  {
    id: 7,
    teacherId: "T-1007",
    name: "Phil Phoden",
    email: "phil.phoden@example.com",
    photo: "/image/noavatar.png",
    address: "202 Cedar St, Springfield, IL",
    dept: "Sales",
    phone: "0198928383",
  },
  {
    id: 8,
    teacherId: "T-1008",
    name: "Tom Cruse",
    email: "tom.cruse@example.com",
    photo: "/image/noavatar.png",
    address: "202 Cedar St, Springfield, IL",
    dept: "Sales",
    phone: "0198928383",
  },
  {
    id: 9,
    teacherId: "T-1009",
    name: "Tom Hanks",
    email: "tom.hanks@example.com",
    photo: "/image/noavatar.png",
    address: "202 Cedar St, Springfield, IL",
    dept: "Sales",
    phone: "0198928383",
  },
  {
    id: 10,
    teacherId: "T-1010",
    name: "Anna Hathaway",
    email: "anna.hathaway@example.com",
    photo: "/image/noavatar.png",
    address: "202 Cedar St, Springfield, IL",
    dept: "Sales",
    phone: "0198928383",
  },
];

export const studentData = [
  {
    id: 1,
    studentId: "S-1000",
    name: "John Doe",
    phone: "123-456-7890",
    classId: "1",
    photo: "/image/noavatar.png",
    address: "123 Main St, Springfield, IL",
  },
  {
    id: 2,
    studentId: "S-1001",
    name: "Jane Smith",
    phone: "123-456-7891",
    classId: "2",
    photo: "/image/noavatar.png",
    address: "123 Main St, Springfield, IL",
  },
  {
    id: 3,
    studentId: "S-1002",
    name: "Mike Johnson",
    phone: "123-456-7892",
    classId: "3",
    photo: "/image/noavatar.png",
    address: "123 Main St, Springfield, IL",
  },
  {
    id: 4,
    studentId: "S-1003",
    name: "Emily Davis",
    phone: "123-456-7893",
    classId: "3",
    photo: "/image/noavatar.png",
    address: "123 Main St, Springfield, IL",
  },
  {
    id: 5,
    studentId: "S-1004",
    name: "Chris Lee",
    phone: "123-456-7894",
    classId: "4",
    photo: "/image/noavatar.png",
    address: "123 Main St, Springfield, IL",
  },
  {
    id: 6,
    studentId: "S-1005",
    name: "Anna Williams",
    phone: "123-456-7895",
    classId: "4",
    photo: "/image/noavatar.png",
    address: "123 Main St, Springfield, IL",
  },
  {
    id: 7,
    studentId: "S-1006",
    name: "David Brown",
    phone: "123-456-7896",
    classId: "4",
    photo: "/image/noavatar.png",
    address: "123 Main St, Springfield, IL",
  },
  {
    id: 8,
    studentId: "S-1007",
    name: "Sophia Wilson",
    phone: "123-456-7897",
    classId: "5",
    photo: "/image/noavatar.png",
    address: "123 Main St, Springfield, IL",
  },
  {
    id: 9,
    studentId: "S-1008",
    name: "James Moore",
    phone: "123-456-7898",
    classId: "6",
    photo: "/image/noavatar.png",
    address: "123 Main St, Springfield, IL",
  },
  {
    id: 10,
    studentId: "S-1009",
    name: "Olivia Taylor",
    phone: "123-456-7899",
    classId: "7",
    photo: "/image/noavatar.png",
    address: "123 Main St, Springfield, IL",
  },
];

export const classData = [
  {
    id: "aaa",
    classId: "C-1000",
    name: "Class 1",
    sections: 2,
    courses: 3,
    students: 20,
  },
  {
    id: "bbb",
    classId: "C-1001",
    name: "Class 2",
    sections: 2,
    courses: 3,
    students: 20,
  },
  {
    id: "ccc",
    classId: "C-1002",
    name: "Class 3",
    sections: 2,
    courses: 4,
    students: 20,
  },
  {
    id: "ddd",
    classId: "C-1003",
    name: "Class 4",
    sections: 2,
    courses: 4,
    students: 20,
  },
  {
    id: "eee",
    classId: "C-1004",
    name: "Class 5",
    sections: 2,
    courses: 5,
    students: 20,
  },
  {
    id: "fff",
    classId: "C-1005",
    name: "Class 6",
    sections: 2,
    courses: 8,
    students: 20,
  },
  {
    id: "ggg",
    classId: "C-1006",
    name: "Class 7",
    sections: 2,
    courses: 9,
    students: 20,
  },
  {
    id: "hhh",
    classId: "C-1007",
    name: "Class 8",
    sections: 2,
    courses: 10,
    students: 20,
  },
  {
    id: "iii",
    classId: "C-1008",
    name: "Class 9",
    sections: 2,
    courses: 11,
    students: 20,
  },
  {
    id: "jjj",
    classId: "C-1009",
    name: "Class 10",
    sections: 2,
    courses: 12,
    students: 20,
  },
];

export const sectionData = [
  {
    id: "aaa",
    sectionId: "S-1000",
    name: "Section A",
    students: 28,
    year: 2024,
    supervisor: "John Doe",
  },
  {
    id: "aab",
    sectionId: "S-1001",
    name: "Section B",
    students: 21,
    year: 2024,
    supervisor: "Jane Smith",
  },
  {
    id: "aac",
    sectionId: "S-1002",
    name: "Section C",
    students: 40,
    year: 2024,
    supervisor: "Anna Smith",
  },
];

export const courseData = [
  {
    id: "aaa",
    courseId: "C-1000",
    courseName: "Course 1",
    enrolledTeacher: "John Doe",
  },
  {
    id: "aab",
    courseId: "C-1001",
    courseName: "Course 2",
    enrolledTeacher: "Jane Smith",
  },
  {
    id: "aac",
    courseId: "C-1002",
    courseName: "Course 3",
    enrolledTeacher: "Anna Smith",
  },
];
